### ISSUE TITLE
Marketplace Install does not work

### ISSUE THREAD

**Issue by andreas-wolf** [JorisAerts/Eclipse-Environment-Variables#6]
No repository found at https://github.com/JorisAerts/Eclipse-Environment-Variables/releases/download/0.0.2/Eclipse-Environment-Variables_0.0.2.jar.

**Comment by chrylis** [comment]
Ran into the same problem. This plugin looks incredibly useful, even in simple form, and I'd love to see it back!

**Comment by JorisAerts** [comment]
I know, it need to fix this; I need to turn my eclipse marketplace jar into some maven artifact. I'll take a look at it.

You should just download that jar and drop it into the eclipse/dropins folder.

A fix is needed for eclipse 2019-06 though, because it's not working anymore (due to some javax.xml.bind dependency), which I'm going to fix, because I use this plugin a lot.

**Comment by imod** [comment]
any chance this get resolved any time soon - fidling around with the dropins directory (wherever this is in Spring Tool Suite is very annoying)

**Comment by jchen5580** [comment]
I tried with the download and dropping the jar into eclipse/dropins approach, the 'Environment Variables' doesn't appear in Preferences. What could be the issue?

**Comment by JorisAerts** [comment]
The marketplace should be fixed any time soon. There is a valid Update Site now, only because of the install failures, the plugin got unlisted.
I send a request to list the plugin again. In the meantime, you can install it from eclipse using the following url:

https://raw.githubusercontent.com/JorisAerts/Eclipse-Update-Site/release/Update-Site/site.xml

**Comment by JorisAerts** [comment]
This should be resolved now.
